name: tests
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: install node v16.13.1
        uses: actions/setup-node@v1
        with:
          node-version: 16.13.1
      - name: yarn install
        run: yarn install
      - name: tsc
        uses: icrawl/action-tsc@v1
        with:
          project: ./tsconfig.json
      - name: run the tests
        run: |
          npm run start &
          sleep 10
          npm run test 